name: animal_crossing
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # manually added below
  flutter_svg: ^2.0.14
  go_router: ^14.4.1
  flutter_staggered_grid_view: ^0.7.0
  path: ^1.9.0
  google_fonts: ^6.2.1
  csv: ^6.0.0
  getwidget: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/pngs/
    - assets/svgs/
    - assets/csvs/